stages:
  annotate_PTEST:
    cmd: python annotate.py --input data/uploads/input_PTEST.csv --output 
      data/outputs/output_PTEST.csv --patient_id PTEST
    deps:
    - data/uploads/input_PTEST.csv
    outs:
    - data/outputs/output_PTEST.csv
  annotate_P001:
    cmd: python annotate.py --input data/uploads/input_P001.csv --output 
      data/outputs/output_P001.csv --patient_id P001
    deps:
    - data/uploads/input_P001.csv
    outs:
    - data/outputs/output_P001.csv
  annotate_P002:
    cmd: python annotate.py --input data/uploads/input_P002.csv --output 
      data/outputs/output_P002.csv --patient_id P002
    deps:
    - data/uploads/input_P002.csv
    outs:
    - data/outputs/output_P002.csv
  annotate_P003:
    cmd: python annotate.py --input data/uploads/input_P003.csv --output 
      data/outputs/output_P003.csv --patient_id P003
    deps:
    - data/uploads/input_P003.csv
    outs:
    - data/outputs/output_P003.csv
